import type { SourceRange } from "../ast/types.js";

export type TokenType =
  | "PROGRAM"
  | "BEGIN"
  | "END"
  | "SET"
  | "LET"
  | "MUT"
  | "DISPLAY"
  | "INPUT"
  | "IF"
  | "THEN"
  | "ELSE"
  | "END-IF"
  | "FOR"
  | "END-FOR"
  | "TO"
  | "STEP"
  | "MATCH"
  | "END-MATCH"
  | "FUNCTION"
  | "ASYNC"
  | "CONST"
  | "RETURN"
  | "END-FUNCTION"
  | "TRAIT"
  | "END-TRAIT"
  | "IMPL"
  | "FOR"
  | "END-IMPL"
  | "ENUM"
  | "MODULE"
  | "END-MODULE"
  | "IMPORT"
  | "EXPORT"
  | "FROM"
  | "AS"
  | "PLUGIN"
  | "MACRO"
  | "END-MACRO"
  | "TEST"
  | "END-TEST"
  | "ASSERT"
  | "UNSAFE"
  | "END-UNSAFE"
  | "SPAWN"
  | "PUBLIC"
  | "TRUE"
  | "FALSE"
  | "IDENTIFIER"
  | "NUMBER"
  | "STRING"
  | "STRING_INTERPOLATION"
  | "DOC_COMMENT"
  | "PLUS"
  | "MINUS"
  | "STAR"
  | "SLASH"
  | "PERCENT"
  | "BANG"
  | "QUESTION"
  | "LESS"
  | "LESS_EQUAL"
  | "GREATER"
  | "GREATER_EQUAL"
  | "ASSIGN"
  | "NOT_EQUAL"
  | "LPAREN"
  | "RPAREN"
  | "LBRACKET"
  | "RBRACKET"
  | "COMMA"
  | "COLON"
  | "DOT"
  | "ARROW"
  | "AMPERSAND"
  | "NEWLINE"
  | "EOF";

export interface Token {
  type: TokenType;
  lexeme: string;
  range: SourceRange;
}

export const KEYWORDS: Record<string, TokenType> = {
  PROGRAM: "PROGRAM",
  BEGIN: "BEGIN",
  END: "END",
  SET: "SET",
  LET: "LET",
  MUT: "MUT",
  DISPLAY: "DISPLAY",
  INPUT: "INPUT",
  IF: "IF",
  THEN: "THEN",
  ELSE: "ELSE",
  "END-IF": "END-IF",
  MATCH: "MATCH",
  "END-MATCH": "END-MATCH",
  FUNCTION: "FUNCTION",
  ASYNC: "ASYNC",
  CONST: "CONST",
  RETURN: "RETURN",
  "END-FUNCTION": "END-FUNCTION",
  TRAIT: "TRAIT",
  "END-TRAIT": "END-TRAIT",
  IMPL: "IMPL",
  FOR: "FOR",
  "END-FOR": "END-FOR",
  TO: "TO",
  STEP: "STEP",
  "END-IMPL": "END-IMPL",
  ENUM: "ENUM",
  MODULE: "MODULE",
  "END-MODULE": "END-MODULE",
  IMPORT: "IMPORT",
  EXPORT: "EXPORT",
  FROM: "FROM",
  AS: "AS",
  PLUGIN: "PLUGIN",
  MACRO: "MACRO",
  "END-MACRO": "END-MACRO",
  TEST: "TEST",
  "END-TEST": "END-TEST",
  ASSERT: "ASSERT",
  UNSAFE: "UNSAFE",
  "END-UNSAFE": "END-UNSAFE",
  SPAWN: "SPAWN",
  PUBLIC: "PUBLIC",
  TRUE: "TRUE",
  FALSE: "FALSE"
};
